apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: proxy 
  namespace: fleet-default
spec:
  repo: https://github.com/cbosdo/fleet-proxy
  branch: main
  paths:
    - metallb
    - metallb/config
    - sealedsecrets
    - proxy-secrets
    - proxy
  targets:
    - name: store1
      clusterSelector:
        matchLabels:
          role: uyuni-proxy
