apiVersion: elemental.cattle.io/v1beta1
kind: MachineInventorySelectorTemplate
metadata:
  name: store1234-machine-selector
  namespace: fleet-default
spec:
  template:
    spec:
      selector:
        matchExpressions:
          - key: serialNumber
            operator: In
            values: [ 'PXY1234' ]
---
kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: store1234-proxy-cluster
  namespace: fleet-default
  labels:
    proxy-ip: 192.168.111.101
    proxy-fqdn: store1234-proxy.world-co.com
    store: store1234
    role: uyuni-proxy
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: store1234-machine-selector
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineGlobalConfig:
      disable:
        - servicelb
        - traefik
  kubernetesVersion: v1.24.8+k3s1
